# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-02-18 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid1', models.IntegerField()),
                ('uid2', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Swiped',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(verbose_name='滑动者id')),
                ('sid', models.IntegerField(verbose_name='被滑动者id')),
                ('flag', models.CharField(choices=[('superlike', '上滑'), ('like', '右滑'), ('dislike', '左滑')], max_length=10, verbose_name='滑动类型')),
                ('dtime', models.DateField(auto_now=True)),
            ],
        ),
    ]
