# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-02-20 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='swiped',
            options={'get_latest_by': 'dtime'},
        ),
        migrations.AlterField(
            model_name='swiped',
            name='dtime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
